### ISSUE TITLE
url facet is too arbitrary

### ISSUE THREAD

**Issue by kptdobe** [adobe/rum-distiller#11]
One regression introduced by the distiller compared the code in rum-explorer: valid urls get "ofuscated" 
 and then unusable.

`https://blog.adobe.com/en/publish/2024/09/11/bringing-gen-ai-to-video-adobe-firefly-video-model-coming-soon` becomes `https://blog.adobe.com/en/publish/2024/09/11/...`

This makes the facet url unusable.

**Comment by trieloff** [comment]
This is intentional, but I can create a `plainURL` facet that does not hide and aggregate noisy values.
