### ISSUE TITLE
url obfuscated because too long creates several issues

### ISSUE THREAD

**Issue by kptdobe** [adobe/rum-distiller#17]
blog.adobe.com has a lot of articles where the url is pretty long (they use the article title as page name). This creates several issues in the reporting:
1. url becomes `/en/publish/2024/10/14/...` which does not allow to identify the page
2. url cannot be used as a link
3. several articles published the same day ends up being the same "url", i.e. all data are grouped

While obfuscating ids or hashes is ok for PII reasons, the length shorting has no valid reason, except maybe aesthetic which should be managed in the consuming application, not in the data.

**Comment by trieloff** [comment]
The length obfuscation is a heuristic, like all others. Of the sites with extra long URL segments, I'd assume blog.adobe.com to be an outlier.

**Comment by trieloff** [comment]
If you don't like the obfuscation, why not just use `plainURL`?

**Comment by kptdobe** [comment]
Well, if I have to change the RUM explorer and Oversight to use plainURL, then URL becomes almost useless no ?

It is not I do not like obfuscation, I do not like the fact it corrupts the data and leads to wrong results. It is not blog.adobe.com specific, but probably a blog site specific issue (business.adobe.com, telegraph.co.uk have the same issue). And that's the ones we have potential stronger need of reporting. Today I cannot share the RUM Explorer with the business users because they do not find their pages.

**Comment by kptdobe** [comment]
oh and this solution is completely arbitrary: do we have a case where we are shortening something more than 60 characters that are something else than a long file name ? I checked multiple domains (adobe.com, telegraph.co.uk, bamboohr...), shorten urls are always valid pages.

**Comment by kptdobe** [comment]
Made a new proposal: if segment length is great than 60 characters, check if the segment follows the pattern:
1. contains only characters, digits, dashes and underscores
2. contains at least 3 dashes or underscores

60 characters would mean at least 4 words, less being suspicious and unexpected.
